project:
  type: book
  resources:
    - "!**/Icon*"

license: "MIT"
  
lang: de


book:
  title: "Analyse der HaNS-Matomo-Daten"
  author: 
    - name: Sebastian Sauer
      orcid: 0000-0003-1515-8348
  date: today
  reader-mode: true      
  repo-actions: [source, issue]
  repo-url: https://github.com/sebastiansauer/hans
  chapters:
    - index.qmd
    - 10-nutzereigenschaften.qmd
    - 20-nutzungszeiten.qmd
    - 30-nutzungsdauer.qmd
    - 40-nutzungsarten.qmd
    - 50-video.qmd
    - 60-llm.qmd

format: 
  html:
    theme:
      light: lumen
      dark: darkly
    embed-resources: true
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Show the code"
    code-tools: true
    code-link: true
    df-print: paged
lightbox: true

execute: 
  warning: false
  cache: true
  freeze: auto
  
params:
   recompute_gt: false