data: "/Users/sebastiansaueruser/FAUbox/HAnS-Ansbach/data-raw"
data_23ws: "/Users/sebastiansaueruser/FAUbox/HAnS-Ansbach/data-raw/23-ws"
data_test: "/Users/sebastiansaueruser/FAUbox/HAnS-Ansbach/data-raw/test"


